export {
  getEnvironmentHttpBaseUrl,
  getSavedEnvironmentRecord,
  getSavedEnvironmentRuntimeState,
  hasSavedEnvironmentRegistryHydrated,
  listSavedEnvironmentRecords,
  resetSavedEnvironmentRegistryStoreForTests,
  resetSavedEnvironmentRuntimeStoreForTests,
  resolveEnvironmentHttpUrl,
  resolveSavedEnvironmentDisplayLabel,
  useSavedEnvironmentRegistryStore,
  useSavedEnvironmentRuntimeStore,
  waitForSavedEnvironmentRegistryHydration,
  type SavedEnvironmentRecord,
  type SavedEnvironmentRuntimeState,
} from "./catalog";

export {
  addSavedEnvironment,
  addManagedRelayEnvironment,
  connectDesktopSshEnvironment,
  disconnectSavedEnvironment,
  ensureEnvironmentConnectionBootstrapped,
  getPrimaryEnvironmentConnection,
  readEnvironmentConnection,
  reconcileSavedEnvironmentConnectionState,
  reconnectSavedEnvironment,
  removeSavedEnvironment,
  requireEnvironmentConnection,
  resetEnvironmentServiceForTests,
  startEnvironmentConnectionService,
  subscribeEnvironmentConnections,
  subscribeProviderInvalidations,
  listEnvironmentConnections,
} from "./service";
export type { EnvironmentConnection } from "@kata-sh/code-client-runtime";
